// ============================
// Demo Data
// ============================
// A rich, realistic dataset used when Firebase is not configured (demo mode).
// All videos point at publicly hosted sample streams so playback actually works:
//   - MP4:  Google "GTv" sample bucket
//   - HLS:  Mux / Akamai public test streams (adaptive bitrate)
// This is a feature, not a placeholder: swap to Firestore automatically when
// FIREBASE_SERVICE_ACCOUNT_KEY is set (see src/lib/repository.ts).

import type {
  Video,
  Category,
  Comment,
  User,
  Analytics,
  WatchHistory,
  Notification,
  LiveStream,
} from '@/types';

// ---------- Categories ----------

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-action', name: 'Action', slug: 'action', description: 'High-octane thrills and explosive set pieces.', image: '', color: '#E50914', videoCount: 0, isActive: true, order: 1, createdAt: '2024-01-01T00:00:00.000Z' },
  { id: 'cat-sci-fi', name: 'Sci-Fi', slug: 'sci-fi', description: 'Futuristic worlds, alien encounters, and mind-bending tech.', image: '', color: '#9C27B0', videoCount: 0, isActive: true, order: 2, createdAt: '2024-01-01T00:00:00.000Z' },
  { id: 'cat-documentary', name: 'Documentaries', slug: 'documentaries', description: 'Real stories, real people, real world.', image: '', color: '#2196F3', videoCount: 0, isActive: true, order: 3, createdAt: '2024-01-01T00:00:00.000Z' },
  { id: 'cat-thriller', name: 'Thriller', slug: 'thriller', description: 'Suspense that keeps you on the edge of your seat.', image: '', color: '#FF5722', videoCount: 0, isActive: true, order: 4, createdAt: '2024-01-01T00:00:00.000Z' },
  { id: 'cat-drama', name: 'Drama', slug: 'drama', description: 'Emotional stories that stay with you.', image: '', color: '#4CAF50', videoCount: 0, isActive: true, order: 5, createdAt: '2024-01-01T00:00:00.000Z' },
  { id: 'cat-kids', name: 'Kids & Family', slug: 'kids-family', description: 'Fun for the whole family.', image: '', color: '#FFC107', videoCount: 0, isActive: true, order: 6, createdAt: '2024-01-01T00:00:00.000Z' },
];

// ---------- Demo Users ----------

const demoUser = (overrides: Partial<User> & Pick<User, 'uid' | 'displayName' | 'email'>): User => ({
  role: 'user',
  emailVerified: true,
  isBanned: false,
  subscription: 'free',
  photoURL: '',
  phoneNumber: undefined,
  createdAt: '2024-01-01T00:00:00.000Z',
  lastLoginAt: '2024-01-01T00:00:00.000Z',
  preferences: {
    autoplay: true,
    autoplayNext: true,
    videoQuality: '1080p',
    subtitlesEnabled: false,
    subtitleLanguage: 'en',
    matureContent: false,
    playNextEpisode: true,
    notifications: { uploads: true, liveStreams: true, comments: true, recommendations: true, marketing: false },
    theme: 'dark',
    language: 'en',
  },
  stats: { totalWatchTime: 0, videosWatched: 0, commentsPosted: 0, followers: 0, following: 0, joinDate: '2024-01-01T00:00:00.000Z' },
  ...overrides,
});

export const DEMO_ADMIN: User = demoUser({
  uid: 'demo-admin',
  email: 'admin@streamflix.dev',
  displayName: 'StreamFlix Admin',
  role: 'admin',
  subscription: 'yearly',
  photoURL: '',
});

export const DEMO_USERS: User[] = [
  DEMO_ADMIN,
  demoUser({ uid: 'demo-user-1', email: 'alex@example.com', displayName: 'Alex Rivera', role: 'teacher', subscription: 'premium' }),
  demoUser({ uid: 'demo-user-2', email: 'sam@example.com', displayName: 'Sam Carter', role: 'student' }),
  demoUser({ uid: 'demo-user-3', email: 'jordan@example.com', displayName: 'Jordan Lee', role: 'user' }),
  demoUser({ uid: 'demo-user-4', email: 'maya@example.com', displayName: 'Maya Patel', role: 'teacher' }),
  demoUser({ uid: 'demo-user-5', email: 'chris@example.com', displayName: 'Chris Nguyen', role: 'user', isBanned: true }),
];

// ---------- Demo Videos ----------

const GTV = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample';
const GTV_IMG = 'https://storage.googleapis.com/gtv-videos-bucket/sample/images';

type VideoSeed = Omit<
  Video,
  'id' | 'category' | 'uploader' | 'thumbnail' | 'videoUrl' | 'hlsUrl' | 'views' | 'likes' | 'dislikes' | 'createdAt' | 'updatedAt' | 'processedQualities' | 'resolution' | 'quality'
> & {
  file: string;
  image: string;
  categoryId: string;
  views: number;
  likes: number;
  dislikes: number;
  createdAt: string;
  hlsUrl?: string;
};

const seedVideos: VideoSeed[] = [
  {
    title: 'Big Buck Bunny',
    description: 'A giant rabbit is being picked on by three rodents, but he is not going to take it anymore. The award-winning open-movie classic, remastered in stunning detail.',
    file: 'BigBuckBunny.mp4',
    image: 'BigBuckBunny.jpg',
    duration: 596,
    categoryId: 'cat-kids',
    tags: ['animation', 'comedy', 'blender'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 158008870,
    format: 'mp4',
    processingProgress: 100,
    views: 14500000,
    likes: 980000,
    dislikes: 8000,
    createdAt: '2024-11-20T10:00:00.000Z',
    hlsUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
  {
    title: 'Sintel',
    description: 'A lonely young woman, Sintel, helps and befriends a dragon, whom she calls Scales. But when he is kidnapped by an unknown force, she sets out on a perilous journey to find him.',
    file: 'Sintel.mp4',
    image: 'Sintel.jpg',
    duration: 888,
    categoryId: 'cat-drama',
    tags: ['fantasy', 'adventure', 'blender'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 179000000,
    format: 'mp4',
    processingProgress: 100,
    views: 12300000,
    likes: 870000,
    dislikes: 6000,
    createdAt: '2024-11-18T10:00:00.000Z',
    hlsUrl: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
  },
  {
    title: 'Tears of Steel',
    description: 'In a future Amsterdam, a group of warriors and scientists fight to bring back the man who once saved the world. A stunning sci-fi short from the Blender Foundation.',
    file: 'TearsOfSteel.mp4',
    image: 'TearsOfSteel.jpg',
    duration: 734,
    categoryId: 'cat-sci-fi',
    tags: ['sci-fi', 'action', 'blender'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 208000000,
    format: 'mp4',
    processingProgress: 100,
    views: 9800000,
    likes: 720000,
    dislikes: 5000,
    createdAt: '2024-11-15T10:00:00.000Z',
    hlsUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
  },
  {
    title: 'Elephants Dream',
    description: 'The very first Blender open movie. Two characters explore a strange, endless machine that may be a dream or a nightmare.',
    file: 'ElephantsDream.mp4',
    image: 'ElephantsDream.jpg',
    duration: 653,
    categoryId: 'cat-sci-fi',
    tags: ['surreal', 'animation', 'blender'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 152000000,
    format: 'mp4',
    processingProgress: 100,
    views: 8200000,
    likes: 610000,
    dislikes: 4000,
    createdAt: '2024-11-12T10:00:00.000Z',
  },
  {
    title: 'Subaru Outback: On Street & Dirt',
    description: 'A cinematic automotive showcase pushing the Subaru Outback through street and off-road conditions.',
    file: 'SubaruOutbackOnStreetAndDirt.mp4',
    image: 'SubaruOutbackOnStreetAndDirt.jpg',
    duration: 595,
    categoryId: 'cat-documentary',
    tags: ['cars', 'automotive', '4k'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 198000000,
    format: 'mp4',
    processingProgress: 100,
    views: 5600000,
    likes: 340000,
    dislikes: 2000,
    createdAt: '2024-11-10T10:00:00.000Z',
  },
  {
    title: 'Volkswagen GTI Review',
    description: 'An in-depth road test and review of the Volkswagen GTI, from the open road to the track.',
    file: 'VolkswagenGTIReview.mp4',
    image: 'VolkswagenGTIReview.jpg',
    duration: 594,
    categoryId: 'cat-documentary',
    tags: ['cars', 'review', 'automotive'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 172000000,
    format: 'mp4',
    processingProgress: 100,
    views: 4100000,
    likes: 290000,
    dislikes: 3000,
    createdAt: '2024-11-08T10:00:00.000Z',
  },
  {
    title: 'We Are Going On Bullrun',
    description: 'Follow the legendary Bullrun rally as supercars tear across America in this adrenaline-fueled documentary.',
    file: 'WeAreGoingOnBullrun.mp4',
    image: 'WeAreGoingOnBullrun.jpg',
    duration: 594,
    categoryId: 'cat-documentary',
    tags: ['cars', 'rally', 'adventure'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 165000000,
    format: 'mp4',
    processingProgress: 100,
    views: 3700000,
    likes: 250000,
    dislikes: 1500,
    createdAt: '2024-11-05T10:00:00.000Z',
  },
  {
    title: 'For Bigger Blazes',
    description: 'A high-energy action sequence that pushes the limits of scale and spectacle.',
    file: 'ForBiggerBlazes.mp4',
    image: 'ForBiggerBlazes.jpg',
    duration: 15,
    categoryId: 'cat-action',
    tags: ['action', 'short'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 2600000,
    format: 'mp4',
    processingProgress: 100,
    views: 21000000,
    likes: 1500000,
    dislikes: 9000,
    createdAt: '2024-11-02T10:00:00.000Z',
  },
  {
    title: 'For Bigger Escapes',
    description: 'A getaway like no other - chase scenes, narrow escapes, and pure adrenaline.',
    file: 'ForBiggerEscapes.mp4',
    image: 'ForBiggerEscapes.jpg',
    duration: 15,
    categoryId: 'cat-action',
    tags: ['action', 'chase'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 2700000,
    format: 'mp4',
    processingProgress: 100,
    views: 19500000,
    likes: 1400000,
    dislikes: 7000,
    createdAt: '2024-10-30T10:00:00.000Z',
  },
  {
    title: 'For Bigger Fun',
    description: 'Pure, unapologetic fun - the short that started it all.',
    file: 'ForBiggerFun.mp4',
    image: 'ForBiggerFun.jpg',
    duration: 60,
    categoryId: 'cat-kids',
    tags: ['fun', 'comedy'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 5600000,
    format: 'mp4',
    processingProgress: 100,
    views: 17800000,
    likes: 1200000,
    dislikes: 6000,
    createdAt: '2024-10-28T10:00:00.000Z',
  },
  {
    title: 'For Bigger Joyrides',
    description: 'A joyride through city streets at maximum speed.',
    file: 'ForBiggerJoyrides.mp4',
    image: 'ForBiggerJoyrides.jpg',
    duration: 15,
    categoryId: 'cat-action',
    tags: ['action', 'cars'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 2500000,
    format: 'mp4',
    processingProgress: 100,
    views: 16200000,
    likes: 1100000,
    dislikes: 5000,
    createdAt: '2024-10-25T10:00:00.000Z',
  },
  {
    title: 'For Bigger Meltdowns',
    description: 'When things go wrong, they go wrong big. A comedic meltdown spectacular.',
    file: 'ForBiggerMeltdowns.mp4',
    image: 'ForBiggerMeltdowns.jpg',
    duration: 15,
    categoryId: 'cat-thriller',
    tags: ['comedy', 'short'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 2400000,
    format: 'mp4',
    processingProgress: 100,
    views: 14900000,
    likes: 1000000,
    dislikes: 4500,
    createdAt: '2024-10-22T10:00:00.000Z',
  },
  {
    title: 'What Car Can You Get For A Grand?',
    description: 'A budget car hunter searches for the best machine money can buy - for under $1000.',
    file: 'WhatCarCanYouGetForAGrand.mp4',
    image: 'WhatCarCanYouGetForAGrand.jpg',
    duration: 595,
    categoryId: 'cat-documentary',
    tags: ['cars', 'budget', 'review'],
    visibility: 'public',
    status: 'ready',
    uploadedBy: 'demo-admin',
    uploaderName: 'StreamFlix Admin',
    uploaderAvatar: '',
    language: 'en',
    ageRestricted: false,
    allowComments: true,
    allowRatings: true,
    captions: [],
    chapters: [],
    fileSize: 168000000,
    format: 'mp4',
    processingProgress: 100,
    views: 4300000,
    likes: 310000,
    dislikes: 2500,
    createdAt: '2024-10-20T10:00:00.000Z',
  },
];

const QUALITY_MAP: Video['quality'] = ['240p', '360p', '480p', '720p', '1080p'];

export function buildDemoVideos(): Video[] {
  return seedVideos.map((seed, index) => {
    const category = DEMO_CATEGORIES.find(c => c.id === seed.categoryId) || DEMO_CATEGORIES[0];
    const isUhd = seed.title === 'Tears of Steel' || seed.title === 'Big Buck Bunny';
    return {
      id: `demo-${index + 1}`,
      title: seed.title,
      description: seed.description,
      thumbnail: `${GTV_IMG}/${seed.image}`,
      thumbnailBlur: `${GTV_IMG}/${seed.image}`,
      videoUrl: `${GTV}/${seed.file}`,
      hlsUrl: seed.hlsUrl,
      duration: seed.duration,
      views: seed.views,
      likes: seed.likes,
      dislikes: seed.dislikes,
      categoryId: seed.categoryId,
      category,
      tags: seed.tags,
      visibility: seed.visibility,
      status: seed.status,
      uploadedBy: seed.uploadedBy,
      uploader: DEMO_ADMIN,
      uploaderName: seed.uploaderName,
      uploaderAvatar: seed.uploaderAvatar,
      language: seed.language,
      ageRestricted: seed.ageRestricted,
      allowComments: seed.allowComments,
      allowRatings: seed.allowRatings,
      captions: seed.captions,
      chapters: seed.chapters,
      quality: isUhd ? [...QUALITY_MAP, '1440p', '4K'] : QUALITY_MAP,
      resolution: { width: 1920, height: 1080, label: '1080p', bitrate: 3000 },
      fileSize: seed.fileSize,
      format: seed.format,
      processedQualities: isUhd ? [...QUALITY_MAP, '1440p', '4K'] : QUALITY_MAP,
      processingProgress: seed.processingProgress,
      createdAt: seed.createdAt,
      updatedAt: seed.createdAt,
    };
  });
}

export const DEMO_VIDEOS: Video[] = buildDemoVideos();

// ---------- Demo Comments ----------

export function buildDemoComments(): Comment[] {
  const now = Date.now();
  const base = (overrides: Partial<Comment> & Pick<Comment, 'id' | 'text'>): Comment => ({
    videoId: 'demo-1',
    userId: 'demo-user-1',
    user: DEMO_USERS[1],
    likes: 0,
    dislikes: 0,
    replies: 0,
    status: 'active',
    isEdited: false,
    createdAt: new Date(now - 86400000).toISOString(),
    ...overrides,
  });

  return [
    base({ id: 'c1', text: 'Absolutely stunning animation - the remaster looks incredible!', likes: 1240, status: 'pinned' }),
    base({ id: 'c2', text: 'The open movie project never ceases to amaze. Great quality streams too.', userId: 'demo-user-3', user: DEMO_USERS[3], likes: 486 }),
    base({ id: 'c3', text: 'Watched this with my kids - they loved it. More like this please!', userId: 'demo-user-2', user: DEMO_USERS[2], likes: 210 }),
    base({ id: 'c4', text: '4K playback was buttery smooth on my setup. Adaptive streaming works great.', userId: 'demo-user-4', user: DEMO_USERS[4], likes: 96 }),
  ];
}

export const DEMO_COMMENTS: Comment[] = buildDemoComments();

// ---------- Demo Watch History ----------

export function buildDemoHistory(): WatchHistory[] {
  return [
    { id: 'h1', userId: 'demo-user', videoId: 'demo-1', video: DEMO_VIDEOS[0], watchedAt: new Date(Date.now() - 3600000).toISOString(), watchDuration: 420, completed: false, lastPosition: 253 },
    { id: 'h2', userId: 'demo-user', videoId: 'demo-3', video: DEMO_VIDEOS[2], watchedAt: new Date(Date.now() - 86400000).toISOString(), watchDuration: 680, completed: true, lastPosition: 734 },
    { id: 'h3', userId: 'demo-user', videoId: 'demo-5', video: DEMO_VIDEOS[4], watchedAt: new Date(Date.now() - 172800000).toISOString(), watchDuration: 95, completed: false, lastPosition: 95 },
  ];
}

export const DEMO_HISTORY: WatchHistory[] = buildDemoHistory();

// ---------- Demo Notifications ----------

export const DEMO_NOTIFICATIONS: Notification[] = [
  { id: 'n1', userId: 'demo-user', type: 'new_video', title: 'New video uploaded', message: 'Big Buck Bunny 4K is now live on the platform.', image: DEMO_VIDEOS[0].thumbnail, link: '/watch/demo-1', isRead: false, createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: 'n2', userId: 'demo-user', type: 'upload', title: 'Upload completed', message: 'Your video "Tears of Steel" finished processing.', link: '/watch/demo-3', isRead: false, createdAt: new Date(Date.now() - 7200000).toISOString() },
  { id: 'n3', userId: 'demo-user', type: 'live_started', title: 'Live stream started', message: 'Alex Rivera started a live class: "Advanced Physics".', isRead: true, createdAt: new Date(Date.now() - 172800000).toISOString() },
];

// ---------- Demo Live Stream ----------

export const DEMO_LIVE_STREAM: LiveStream = {
  id: 'live-demo-1',
  title: 'Advanced Physics Live Class',
  description: 'Interactive live session covering quantum mechanics basics. Ask questions in chat!',
  thumbnail: DEMO_VIDEOS[2].thumbnail,
  teacherId: 'demo-user-1',
  teacher: DEMO_USERS[1],
  status: 'idle',
  viewers: 0,
  maxViewers: 500,
  duration: 0,
  chatEnabled: true,
  recordingEnabled: true,
  screenShareEnabled: true,
  whiteboardEnabled: true,
  raiseHandEnabled: true,
  muteAllEnabled: true,
  streamKey: 'demo-stream-key',
  rtmpUrl: 'rtmp://live.example.com/live',
  chatMessages: [],
  participants: [],
  isRecording: false,
  createdAt: new Date().toISOString(),
};

// ---------- Demo Analytics ----------

export function buildDemoAnalytics(): Analytics {
  return {
    dailyUsers: [842, 930, 1012, 987, 1105, 1240, 1380, 1310, 1455, 1520, 1688, 1740],
    mostWatched: DEMO_VIDEOS.slice(0, 5),
    watchTime: 184300,
    revenue: 48250,
    topCategories: DEMO_CATEGORIES.slice(0, 4),
    storageUsage: 245 * 1024 * 1024 * 1024,
    bandwidthUsage: 1.2 * 1024 * 1024 * 1024 * 1024,
    userGrowth: [1020, 1080, 1140, 1210, 1290, 1380, 1460, 1530, 1620, 1710, 1820, 1940],
    videoUploads: [12, 18, 14, 22, 17, 25, 21, 28, 24, 31, 27, 34],
    activeStreams: 3,
    totalVideos: DEMO_VIDEOS.length,
    totalUsers: 125430,
    totalComments: 4823,
  };
}

export const DEMO_ANALYTICS: Analytics = buildDemoAnalytics();
